version: '3.8'

services:
  postgres:
    container_name: db
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: bix
      POSTGRES_PASSWORD: tech
      POSTGRES_DB: vendas
    ports:
      - "5500:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  db_data: {}